import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav style={{width:"100%", background: "#9c232c", fontSize: "50px", display:"flex" , justifyContent: "center"}}>
        <Link style={{margin: "6px"}}href="/">Home</Link>
        <Link style={{margin: "6px"}}href="/posts">Posts</Link>
        <Link style={{margin: "6px"}}href="/articles">Articles Page</Link>

        </nav>
        {children}</body>
    </html>
  );
}
